<?php

// Data functions (insert, update, delete, form) for table budgets

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function budgets_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('budgets');
	if(!$arrPerm['insert']) return false;

	$data = [
		'convention' => Request::lookup('convention', ''),
		'type' => Request::lookup('type', ''),
		'precision' => Request::val('precision', ''),
		'accorde' => Request::val('accorde', ''),
		'notes' => Request::val('notes', ''),
		'verse' => Request::val('verse', ''),
		'reste_verser' => Request::val('reste_verser', ''),
		'ouvert' => Request::val('ouvert', ''),
		'reste_ouvrir' => Request::val('reste_ouvrir', ''),
		'non_liquide' => Request::val('non_liquide', ''),
		'liquide' => Request::val('liquide', ''),
		'utilise' => Request::val('utilise', ''),
		'disponible' => Request::val('disponible', ''),
		'reste_engager' => Request::val('reste_engager', ''),
		'reservation_salaire' => Request::val('reservation_salaire', ''),
		'reste_depenser' => Request::val('reste_depenser', ''),
		'prop_uo' => Request::val('prop_uo', ''),
		'prop_uv' => Request::val('prop_uv', ''),
		'prop_ua' => Request::val('prop_ua', ''),
	];

	if($data['convention'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Convention': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['type'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Type': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['accorde'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Accord&#233;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: budgets_before_insert
	if(function_exists('budgets_before_insert')) {
		$args = [];
		if(!budgets_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('budgets', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('budgets', $recID, calculated_fields()['budgets']);

	// hook: budgets_after_insert
	if(function_exists('budgets_after_insert')) {
		$res = sql("SELECT * FROM `budgets` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!budgets_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('budgets', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) budgets_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function budgets_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function budgets_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('budgets', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: budgets_before_delete
	if(function_exists('budgets_before_delete')) {
		$args = [];
		if(!budgets_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: versements
	$res = sql("SELECT `id` FROM `budgets` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `versements` WHERE `ligne_budgetaire`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'versements', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'versements', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: lignes_credits
	$res = sql("SELECT `id` FROM `budgets` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `lignes_credits` WHERE `ligne_budgetaire`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'lignes_credits', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'lignes_credits', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: credits
	$res = sql("SELECT `id` FROM `budgets` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `credits` WHERE `ligne_budgetaire`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'credits', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'credits', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: recrutements
	$res = sql("SELECT `id` FROM `budgets` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `recrutements` WHERE `ligne_budgetaire`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'recrutements', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'recrutements', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: depenses
	$res = sql("SELECT `id` FROM `budgets` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `depenses` WHERE `ligne_budgetaire`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'depenses', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'depenses', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'budgets_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `budgets` WHERE `id`='{$selected_id}'", $eo);

	// hook: budgets_after_delete
	if(function_exists('budgets_after_delete')) {
		$args = [];
		budgets_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='budgets' AND `pkValue`='{$selected_id}'", $eo);
}

function budgets_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('budgets', $selected_id, 'edit')) return false;

	$data = [
		'convention' => Request::lookup('convention', ''),
		'type' => Request::lookup('type', ''),
		'precision' => Request::val('precision', ''),
		'accorde' => Request::val('accorde', ''),
		'notes' => Request::val('notes', ''),
		'verse' => Request::val('verse', ''),
		'reste_verser' => Request::val('reste_verser', ''),
		'ouvert' => Request::val('ouvert', ''),
		'reste_ouvrir' => Request::val('reste_ouvrir', ''),
		'non_liquide' => Request::val('non_liquide', ''),
		'liquide' => Request::val('liquide', ''),
		'utilise' => Request::val('utilise', ''),
		'disponible' => Request::val('disponible', ''),
		'reste_engager' => Request::val('reste_engager', ''),
		'reservation_salaire' => Request::val('reservation_salaire', ''),
		'reste_depenser' => Request::val('reste_depenser', ''),
		'prop_uo' => Request::val('prop_uo', ''),
		'prop_uv' => Request::val('prop_uv', ''),
		'prop_ua' => Request::val('prop_ua', ''),
	];

	if($data['convention'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Convention': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['type'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Type': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['accorde'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Accord&#233;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('budgets', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: budgets_before_update
	if(function_exists('budgets_before_update')) {
		$args = ['old_data' => $old_data];
		if(!budgets_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'budgets', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="budgets_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('budgets', $data['selectedID'], calculated_fields()['budgets']);

	// hook: budgets_after_update
	if(function_exists('budgets_after_update')) {
		$res = sql("SELECT * FROM `budgets` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!budgets_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='budgets' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function budgets_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('budgets');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_convention = thisOr($_REQUEST['filterer_convention'], '');
	$filterer_type = thisOr($_REQUEST['filterer_type'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: convention
	$combo_convention = new DataCombo;
	// combobox: type
	$combo_type = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='budgets' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='budgets' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `budgets` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'budgets_view.php', false);
		}
		$combo_convention->SelectedData = $row['convention'];
		$combo_type->SelectedData = $row['type'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_convention->SelectedData = $filterer_convention;
		$combo_type->SelectedData = $filterer_type;
	}
	$combo_convention->HTML = '<span id="convention-container' . $rnd1 . '"></span><input type="hidden" name="convention" id="convention' . $rnd1 . '" value="' . html_attr($combo_convention->SelectedData) . '">';
	$combo_convention->MatchText = '<span id="convention-container-readonly' . $rnd1 . '"></span><input type="hidden" name="convention" id="convention' . $rnd1 . '" value="' . html_attr($combo_convention->SelectedData) . '">';
	$combo_type->HTML = $combo_type->MatchText = '<span id="type-container' . $rnd1 . '"></span>';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_convention__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['convention'] : htmlspecialchars($filterer_convention, ENT_QUOTES)); ?>"};
		AppGini.current_type__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['type'] : htmlspecialchars($filterer_type, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(convention_reload__RAND__) == 'function') convention_reload__RAND__();
				if(typeof(type_reload__RAND__) == 'function') type_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function convention_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#convention-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_convention__RAND__.value, t: 'budgets', f: 'convention' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="convention"]').val(resp.results[0].id);
							$j('[id=convention-container-readonly__RAND__]').html('<span id="convention-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=conventions_view_parent]').hide(); } else { $j('.btn[id=conventions_view_parent]').show(); }


							if(typeof(convention_update_autofills__RAND__) == 'function') convention_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'budgets', f: 'convention' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_convention__RAND__.value = e.added.id;
				AppGini.current_convention__RAND__.text = e.added.text;
				$j('[name="convention"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=conventions_view_parent]').hide(); } else { $j('.btn[id=conventions_view_parent]').show(); }


				if(typeof(convention_update_autofills__RAND__) == 'function') convention_update_autofills__RAND__();
			});

			if(!$j("#convention-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_convention__RAND__.value, t: 'budgets', f: 'convention' },
					success: function(resp) {
						$j('[name="convention"]').val(resp.results[0].id);
						$j('[id=convention-container-readonly__RAND__]').html('<span id="convention-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=conventions_view_parent]').hide(); } else { $j('.btn[id=conventions_view_parent]').show(); }

						if(typeof(convention_update_autofills__RAND__) == 'function') convention_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_convention__RAND__.value, t: 'budgets', f: 'convention' },
				success: function(resp) {
					$j('[id=convention-container__RAND__], [id=convention-container-readonly__RAND__]').html('<span id="convention-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=conventions_view_parent]').hide(); } else { $j('.btn[id=conventions_view_parent]').show(); }

					if(typeof(convention_update_autofills__RAND__) == 'function') convention_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function type_reload__RAND__() {
			$j.ajax({
				url: 'ajax_combo.php',
				data: {
					t: 'budgets',
					f: 'type',
					id: AppGini.current_type__RAND__.value,
					text: AppGini.current_type__RAND__.text,
					o: <?php echo (($AllowUpdate || $AllowInsert) && !$dvprint ? '1' : '0'); ?>

				},
				success: function(html) {
					$j('#type-container__RAND__').html(html);
				},
				complete: function() { type_changed__RAND__() },
			});
		}

		function type_changed__RAND__() {
			if($j("input[name=type]").length) {
				if($j("input[name=type]:checked").length) {
					AppGini.current_type__RAND__.value = $j("input[name=type]:checked").val();
					AppGini.current_type__RAND__.text = "";
				} else {
					AppGini.current_type__RAND__.value = "";
					AppGini.current_type__RAND__.text = "";
				}
				AppGini.hideViewParentLinks();
			}

			if(typeof(type_update_autofills__RAND__) == 'function') type_update_autofills__RAND__();
		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/budgets_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/budgets_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Ligne budg&#233;taire', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return budgets_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return budgets_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return budgets_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#convention').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#convention_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#type').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#type_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#precision').replaceWith('<div class=\"form-control-static\" id=\"precision\">' + (jQuery('#precision').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#accorde').replaceWith('<div class=\"form-control-static\" id=\"accorde\">' + (jQuery('#accorde').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#verse').replaceWith('<div class=\"form-control-static\" id=\"verse\">' + (jQuery('#verse').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reste_verser').replaceWith('<div class=\"form-control-static\" id=\"reste_verser\">' + (jQuery('#reste_verser').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ouvert').replaceWith('<div class=\"form-control-static\" id=\"ouvert\">' + (jQuery('#ouvert').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reste_ouvrir').replaceWith('<div class=\"form-control-static\" id=\"reste_ouvrir\">' + (jQuery('#reste_ouvrir').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#non_liquide').replaceWith('<div class=\"form-control-static\" id=\"non_liquide\">' + (jQuery('#non_liquide').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#liquide').replaceWith('<div class=\"form-control-static\" id=\"liquide\">' + (jQuery('#liquide').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#utilise').replaceWith('<div class=\"form-control-static\" id=\"utilise\">' + (jQuery('#utilise').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#disponible').replaceWith('<div class=\"form-control-static\" id=\"disponible\">' + (jQuery('#disponible').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reste_engager').replaceWith('<div class=\"form-control-static\" id=\"reste_engager\">' + (jQuery('#reste_engager').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reservation_salaire').replaceWith('<div class=\"form-control-static\" id=\"reservation_salaire\">' + (jQuery('#reservation_salaire').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reste_depenser').replaceWith('<div class=\"form-control-static\" id=\"reste_depenser\">' + (jQuery('#reste_depenser').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#prop_uo').replaceWith('<div class=\"form-control-static\" id=\"prop_uo\">' + (jQuery('#prop_uo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#prop_uv').replaceWith('<div class=\"form-control-static\" id=\"prop_uv\">' + (jQuery('#prop_uv').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#prop_ua').replaceWith('<div class=\"form-control-static\" id=\"prop_ua\">' + (jQuery('#prop_ua').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(convention)%%>', $combo_convention->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(convention)%%>', $combo_convention->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(convention)%%>', urlencode($combo_convention->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(type)%%>', $combo_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(type)%%>', $combo_type->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(type)%%>', urlencode($combo_type->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('convention' => array('conventions', 'Convention'), 'type' => array('types_ligne', 'Type'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(convention)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(precision)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(accorde)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(notes)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(verse)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reste_verser)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ouvert)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reste_ouvrir)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(non_liquide)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(liquide)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utilise)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(disponible)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reste_engager)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reservation_salaire)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reste_depenser)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prop_uo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prop_uv)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prop_ua)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(convention)%%>', safe_html($urow['convention']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(convention)%%>', html_attr($row['convention']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(convention)%%>', urlencode($urow['convention']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', safe_html($urow['type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', html_attr($row['type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(precision)%%>', safe_html($urow['precision']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(precision)%%>', html_attr($row['precision']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precision)%%>', urlencode($urow['precision']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(accorde)%%>', safe_html($urow['accorde']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(accorde)%%>', html_attr($row['accorde']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accorde)%%>', urlencode($urow['accorde']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5">' . html_attr($row['notes']) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<div id="notes" class="form-control-static">' . $row['notes'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(notes)%%>', nl2br($row['notes']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notes)%%>', urlencode($urow['notes']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(verse)%%>', safe_html($urow['verse']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(verse)%%>', html_attr($row['verse']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verse)%%>', urlencode($urow['verse']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reste_verser)%%>', safe_html($urow['reste_verser']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reste_verser)%%>', html_attr($row['reste_verser']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_verser)%%>', urlencode($urow['reste_verser']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ouvert)%%>', safe_html($urow['ouvert']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ouvert)%%>', html_attr($row['ouvert']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ouvert)%%>', urlencode($urow['ouvert']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reste_ouvrir)%%>', safe_html($urow['reste_ouvrir']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reste_ouvrir)%%>', html_attr($row['reste_ouvrir']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_ouvrir)%%>', urlencode($urow['reste_ouvrir']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(non_liquide)%%>', safe_html($urow['non_liquide']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(non_liquide)%%>', html_attr($row['non_liquide']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(non_liquide)%%>', urlencode($urow['non_liquide']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(liquide)%%>', safe_html($urow['liquide']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(liquide)%%>', html_attr($row['liquide']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(liquide)%%>', urlencode($urow['liquide']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utilise)%%>', safe_html($urow['utilise']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utilise)%%>', html_attr($row['utilise']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utilise)%%>', urlencode($urow['utilise']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(disponible)%%>', safe_html($urow['disponible']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(disponible)%%>', html_attr($row['disponible']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(disponible)%%>', urlencode($urow['disponible']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reste_engager)%%>', safe_html($urow['reste_engager']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reste_engager)%%>', html_attr($row['reste_engager']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_engager)%%>', urlencode($urow['reste_engager']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reservation_salaire)%%>', safe_html($urow['reservation_salaire']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reservation_salaire)%%>', html_attr($row['reservation_salaire']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reservation_salaire)%%>', urlencode($urow['reservation_salaire']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reste_depenser)%%>', safe_html($urow['reste_depenser']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reste_depenser)%%>', html_attr($row['reste_depenser']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_depenser)%%>', urlencode($urow['reste_depenser']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prop_uo)%%>', safe_html($urow['prop_uo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prop_uo)%%>', html_attr($row['prop_uo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_uo)%%>', urlencode($urow['prop_uo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prop_uv)%%>', safe_html($urow['prop_uv']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prop_uv)%%>', html_attr($row['prop_uv']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_uv)%%>', urlencode($urow['prop_uv']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prop_ua)%%>', safe_html($urow['prop_ua']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prop_ua)%%>', html_attr($row['prop_ua']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_ua)%%>', urlencode($urow['prop_ua']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(convention)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(convention)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(precision)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(precision)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(accorde)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(accorde)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(verse)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verse)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reste_verser)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_verser)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ouvert)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ouvert)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reste_ouvrir)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_ouvrir)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(non_liquide)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(non_liquide)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(liquide)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(liquide)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utilise)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utilise)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(disponible)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(disponible)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reste_engager)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_engager)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reservation_salaire)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reservation_salaire)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reste_depenser)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reste_depenser)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prop_uo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_uo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prop_uv)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_uv)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prop_ua)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prop_ua)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('budgets');
	if($selected_id) {
		$jdata = get_joined_record('budgets', $selected_id);
		if($jdata === false) $jdata = get_defaults('budgets');
		$rdata = $row;
	}
	$templateCode .= loadView('budgets-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: budgets_dv
	if(function_exists('budgets_dv')) {
		$args=[];
		budgets_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}